// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateZip(arg1, arg2) {
  return window['go']['main']['App']['CreateZip'](arg1, arg2);
}

export function DecryptAndExtractCapsule(arg1, arg2, arg3) {
  return window['go']['main']['App']['DecryptAndExtractCapsule'](arg1, arg2, arg3);
}

export function DecryptFile(arg1, arg2) {
  return window['go']['main']['App']['DecryptFile'](arg1, arg2);
}

export function EncryptFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EncryptFile'](arg1, arg2, arg3, arg4);
}

export function EncryptFiles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EncryptFiles'](arg1, arg2, arg3, arg4);
}

export function ExtractZip(arg1, arg2) {
  return window['go']['main']['App']['ExtractZip'](arg1, arg2);
}

export function GetCurrentDirectory() {
  return window['go']['main']['App']['GetCurrentDirectory']();
}

export function SelectEncryptedFile() {
  return window['go']['main']['App']['SelectEncryptedFile']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function ValidatePassword(arg1) {
  return window['go']['main']['App']['ValidatePassword'](arg1);
}
