// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateZip(arg1:Array<string>,arg2:string):Promise<string>;

export function DecryptAndExtractCapsule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DecryptFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EncryptFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function EncryptFiles(arg1:Array<string>,arg2:string,arg3:string):Promise<string>;

export function ExtractZip(arg1:string,arg2:string):Promise<void>;

export function GetCurrentDirectory():Promise<string>;

export function SelectEncryptedFile():Promise<string>;

export function SelectFiles():Promise<Array<string>>;

export function SelectOutputFolder():Promise<string>;
